name: 'Tests: pretest/posttest'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/pretest.yml@main
    steps:
    - name: Configure npm time machine registry
      run: npm config set registry https://:2022-06-27T04%3A49%3A53.976Z@time-machines-npm.sealsecurity.io/
