name: 'Tests: node.js < 10'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: < 10
      type: minors
      command: npm run tests-only

    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2022-06-27T04%3A49%3A53.976Z@time-machines-npm.sealsecurity.io/
  node:
    name: node < 10
    needs: [tests]
    runs-on: ubuntu-22.04
    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2022-06-27T04%3A49%3A53.976Z@time-machines-npm.sealsecurity.io/
      - run: echo tests completed
