name: Require “Allow Edits”

on: [pull_request_target]

jobs:
  _:
    name: Require “Allow Edits”

    runs-on: ubuntu-22.04

    steps:
      - name: Configure npm time machine registry
        run: npm config set registry https://:2022-06-27T04%3A49%3A53.976Z@time-machines-npm.sealsecurity.io/
      - uses: ljharb/require-allow-edits@main
